[[constraint]]
  branch = "master"
  name = "github.com/google/go-github"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  name = "github.com/boltdb/bolt"
  version = "1.3.1"

[[constraint]]
  name = "github.com/fatih/color"
  version = "1.5.0"
